name: Publish to Maven Central
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: gradle
      #          server-id: 'central'
      #          server-username: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      #          server-password: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
      #          gpg-private-key: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      #          gpg-passphrase: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish package to local staging directory
        run: ./gradlew publish
      - name: Publish package to maven central
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          # This used by JReleaser to create a Github release, I believe
          JRELEASER_GITHUB_TOKEN: ${{ github.token }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
        run: ./gradlew jreleaserFullRelease --stacktrace
